# Generated by Django 3.2 on 2021-04-25 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_category_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.TextField(default=1, verbose_name='About Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='Person address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='category_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='children.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Person Born Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='disease',
            field=models.TextField(default=1, verbose_name='Name of disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=1, max_length=70, unique=True, verbose_name='Person Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Person Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Person Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Person Middle name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=1, max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default=1, upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.category', verbose_name='Category'), verbose_name='Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.SlugField(default=1, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
