# Generated by Django 3.2 on 2021-04-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20210425_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Person Born Date'),
        ),
    ]
