# Generated by Django 3.2 on 2021-04-30 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Armenia', max_length=40, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
